const iodev = {
  categories: ['web', 'ui/ux'],
  projects: [
    {
      id: 1,
      name: 'Naikdaun',
      slug: 'naikdaun',
      category: 'web',
      year: 2021,
      bannerColor: '#391A8F',
      heroImage: '/images/projects/naikdaun.jpg',
    },
    {
      id: 2,
      name: 'Scooter Work Shop',
      slug: 'scooter-work-shop',
      category: 'web',
      year: 2021,
      bannerColor: '#353535',
      heroImage: '/images/projects/2.jpg',
    },
    {
      id: 3,
      name: 'Slow Motor Inventory',
      slug: 'slow-motor-inventory',
      category: 'web',
      year: 2021,
      bannerColor: '#353741',
      heroImage: '/images/projects/3.jpg',
    },
    {
      id: 4,
      name: 'Project Four',
      slug: 'project-four',
      category: 'web',
      year: 2021,
      bannerColor: '#363638',
      heroImage: '/images/projects/4.jpg',
    },
    {
      id: 5,
      name: 'Project Five',
      slug: 'project-five',
      category: 'ui/ux',
      year: 2021,
      bannerColor: '#3E3F42',
      heroImage: '/images/projects/5.jpg',
    },
    {
      id: 6,
      name: 'Project Six',
      slug: 'project-six',
      category: 'ui/ux',
      year: 2021,
      bannerColor: '#BA0E28',
      heroImage: '/images/projects/6.jpg',
    },
    {
      id: 7,
      name: 'Project Seven',
      slug: 'project-seven',
      category: 'ui/ux',
      year: 2021,
      bannerColor: '#008BFF',
      heroImage: '/images/projects/7.jpg',
    },
  ],
};

export default iodev;
